from app import db
from .product import Product
from .category import Category
from .customer import Customer
from .waiter import Waiter
from .table import Table
from .order import Order
from .order_item import OrderItem
from .payment import Payment
